//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        [Key]
        public int Task_Id { get; set; }
        public string Task_Name { get; set; }
        public string Task_Preparation { get; set; }
        public Nullable<int> Task_Duration { get; set; }
        public string Task_Status { get; set; }
        public Nullable<int> Task_FamilyMemberId { get; set; }
    
        public virtual FamilyMember FamilyMember { get; set; }
    }
}
